import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:moean/core/errors/failures.dart';
import 'package:moean/features/exam_generation/domain/entities/exam_entities.dart';
import 'package:moean/features/exam_generation/domain/usecases/generate_exam_usecase.dart';

abstract class GenerateExamState {}

class GenerateExamInitial extends GenerateExamState {}

class GenerateExamLoading extends GenerateExamState {}

class GenerateExamSuccess extends GenerateExamState {
  final ExamEntity exam;
  GenerateExamSuccess(this.exam);
}

class GenerateExamError extends GenerateExamState {
  final String message;
  GenerateExamError(this.message);
}

class GenerateExamPaymentRequired extends GenerateExamState {
  final String message;
  final String code;
  GenerateExamPaymentRequired(this.message, this.code);
}

class GenerateExamCubit extends Cubit<GenerateExamState> {
  final GenerateExamUseCase generateExamUseCase;

  GenerateExamCubit(this.generateExamUseCase) : super(GenerateExamInitial());

  Future<void> generate({
    String? title,
    required String grade,
    required String subject,
    required List<Map<String, dynamic>> lessons,
    required Map<int, RequestedCountsEntity> counts,
    Map<int, List<int>>? selectedQuestionIds,
  }) async {
    if (!isClosed) emit(GenerateExamLoading());

    // Map the selected lessons with their respective requested counts to match the API contract
    final List<Map<String, dynamic>> requestedLessons = [];
    for (final lesson in lessons) {
      final id = lesson['id'] as int;
      final requestedCounts = counts[id];
      final selectedIds = selectedQuestionIds?[id] ?? [];
      
      if (requestedCounts != null || selectedIds.isNotEmpty) {
        requestedLessons.add({
          'lesson_id': id,
          'lesson_name': lesson['name'],
          if (selectedIds.isNotEmpty) 'selected_question_ids': selectedIds,
          'requested_counts': {
            'mcq': requestedCounts?.mcq ?? 0,
            'true_false': requestedCounts?.trueFalse ?? 0,
            'fill_blank': requestedCounts?.fillBlank ?? 0,
            'essay': requestedCounts?.essay ?? 0,
            'matching': requestedCounts?.matching ?? 0,
          }
        });
      }
    }

    final result = await generateExamUseCase.execute(
      title: title ?? '', // Title will be auto-generated by the backend if empty
      grade: grade,
      subject: subject,
      lessons: requestedLessons,
    );

    if (isClosed) return;

    result.fold(
      (failure) {
        if (!isClosed) {
          if (failure is PaymentRequiredFailure) {
            emit(GenerateExamPaymentRequired(failure.message, failure.code));
          } else {
            emit(GenerateExamError(failure.message));
          }
        }
      },
      (exam) {
        if (!isClosed) emit(GenerateExamSuccess(exam));
      },
    );
  }
}
