import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:moean/features/exam_generation/domain/entities/exam_entities.dart';
import 'package:moean/features/exam_generation/domain/usecases/generate_exam_usecase.dart';

abstract class GenerateExamState {}

class GenerateExamInitial extends GenerateExamState {}

class GenerateExamLoading extends GenerateExamState {}

class GenerateExamSuccess extends GenerateExamState {
  final ExamEntity exam;
  GenerateExamSuccess(this.exam);
}

class GenerateExamError extends GenerateExamState {
  final String message;
  GenerateExamError(this.message);
}

class GenerateExamCubit extends Cubit<GenerateExamState> {
  final GenerateExamUseCase generateExamUseCase;

  GenerateExamCubit(this.generateExamUseCase) : super(GenerateExamInitial());

  Future<void> generate({
    required String grade,
    required String subject,
    required List<Map<String, dynamic>> lessons,
    required Map<int, RequestedCountsEntity> counts,
  }) async {
    emit(GenerateExamLoading());

    // Map the selected lessons with their respective requested counts to match the API contract
    final List<Map<String, dynamic>> requestedLessons = [];
    for (final lesson in lessons) {
      final id = lesson['id'] as int;
      final requestedCounts = counts[id];
      if (requestedCounts != null) {
        requestedLessons.add({
          'lesson_id': id,
          'lesson_name': lesson['name'],
          'requested_counts': {
            'mcq': requestedCounts.mcq,
            'true_false': requestedCounts.trueFalse,
            'fill_blank': requestedCounts.fillBlank,
            'essay': requestedCounts.essay,
            'matching': requestedCounts.matching,
          }
        });
      }
    }

    final result = await generateExamUseCase.execute(
      title: '', // Title will be auto-generated by the backend if empty
      grade: grade,
      subject: subject,
      lessons: requestedLessons,
    );

    result.fold(
      (failure) => emit(GenerateExamError(failure.message)),
      (exam) => emit(GenerateExamSuccess(exam)),
    );
  }
}
